# Generated by Django 5.0.1 on 2024-01-30 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_items', to='webapp.like')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleLikedItem',
            fields=[
                ('likeditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.likeditem')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liked_item', to='webapp.article')),
            ],
            bases=('webapp.likeditem',),
        ),
        migrations.CreateModel(
            name='CommentLikedItem',
            fields=[
                ('likeditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.likeditem')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liked_item', to='webapp.comment')),
            ],
            bases=('webapp.likeditem',),
        ),
    ]
